import {test,expect,loginPage} from './fixtures.js';
import {forgeId} from '@azerish25-ux/forgeqa-playwright';

test('owner signs in, creates a project and task, then signs out',{tag:'@smoke',annotation:forgeId('tb-ui-owner')},async({page,tenant,owner})=>{
  await loginPage(page,tenant);await page.getByLabel('New project',{exact:true}).fill('Release readiness');await page.getByRole('button',{name:'Create project',exact:true}).click();await expect(page.getByRole('heading',{name:'Release readiness'})).toBeVisible();
  await page.getByLabel('Task title',{exact:true}).fill('Review initial failure evidence');await page.getByRole('button',{name:'Create task',exact:true}).click();await expect(page.getByRole('heading',{name:'Review initial failure evidence',exact:true})).toBeVisible();
  const projects=await(await owner.get(`/api/workspaces/${tenant.workspaceId}/projects`)).json();const p=projects.find((v:{name:string})=>v.name==='Release readiness');expect(p).toBeTruthy();const tasks=await(await owner.get(`/api/projects/${p.id}/tasks`)).json();expect(tasks.items[0].title).toBe('Review initial failure evidence');
  await page.getByRole('button',{name:'Sign out'}).click();await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();
});
test('editor updates task while viewer sees a read-only workspace',{tag:'@regression',annotation:forgeId('tb-ui-roles')},async({page,tenant,owner})=>{
  await owner.post(`/api/projects/${tenant.projectId}/tasks`,{data:{title:'Review contract'}});await loginPage(page,tenant,'editor');await page.getByRole('button',{name:'Edit Review contract',exact:true}).click();await page.getByLabel('Task title',{exact:true}).fill('Contract reviewed');await page.getByLabel('Task status',{exact:true}).selectOption('done');await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByRole('heading',{name:'Contract reviewed',exact:true})).toBeVisible();const saved=await(await owner.get(`/api/projects/${tenant.projectId}/tasks`)).json();expect(saved.items.find((task:{title:string})=>task.title==='Contract reviewed').status).toBe('done');await page.getByRole('button',{name:'Sign out'}).click();await loginPage(page,tenant,'viewer');await expect(page.getByText('Viewer access:',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Create task',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Contract reviewed',exact:true})).toBeVisible();
});
test('feature flag enables upload and browser download; native clock changes only display',{tag:'@release',annotation:forgeId('tb-ui-files-clock')},async({page,tenant,owner})=>{
  const task=await(await owner.post(`/api/projects/${tenant.projectId}/tasks`,{data:{title:'Time-sensitive task',dueAt:'2030-01-01T00:00:00Z'}})).json();
  await page.clock.setFixedTime(new Date('2031-01-01T00:00:00Z'));await loginPage(page,tenant);await expect(page.getByText(/Overdue:/)).toBeVisible();await page.getByText('Membership & settings',{exact:true}).click();await page.getByLabel('Enable attachments').check();await expect(page.getByLabel('Enable attachments')).toBeChecked();await expect.poll(async()=>{const workspaces=await(await owner.get('/api/workspaces')).json();return workspaces[0].attachments_enabled;}).toBe(true);
  await page.getByLabel('Enable attachments').uncheck();await expect(page.getByLabel('Enable attachments')).not.toBeChecked();await expect.poll(async()=>{const workspaces=await(await owner.get('/api/workspaces')).json();return workspaces[0].attachments_enabled;}).toBe(false);
  await page.getByLabel('Enable attachments').check();await expect.poll(async()=>{const workspaces=await(await owner.get('/api/workspaces')).json();return workspaces[0].attachments_enabled;}).toBe(true);await page.reload();await page.getByText('Membership & settings',{exact:true}).click();await expect(page.getByLabel('Enable attachments')).toBeChecked();
  await page.getByRole('button',{name:'Edit Time-sensitive task',exact:true}).click();await page.getByLabel('Attach file (up to 64 KB)').setInputFiles({name:'evidence.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic browser upload')});await expect(page.getByRole('link',{name:'evidence.txt'})).toBeVisible();const downloaded=page.waitForEvent('download');await page.getByRole('link',{name:'evidence.txt'}).click();const download=await downloaded;expect(download.suggestedFilename()).toBe('evidence.txt');expect(await download.failure()).toBeNull();const stream=await download.createReadStream();const chunks:Buffer[]=[];for await(const chunk of stream)chunks.push(Buffer.from(chunk));expect(Buffer.concat(chunks).toString('utf8')).toBe('Synthetic browser upload');
  const exportLink=page.getByRole('link',{name:'Export CSV'});await expect(exportLink).toHaveAttribute('download','tasks.csv');const csvDownloaded=page.waitForEvent('download');await exportLink.click();const csv=await csvDownloaded;expect(csv.suggestedFilename()).toBe('tasks.csv');expect(await csv.failure()).toBeNull();const csvStream=await csv.createReadStream();const csvChunks:Buffer[]=[];for await(const chunk of csvStream)csvChunks.push(Buffer.from(chunk));expect(Buffer.concat(csvChunks).toString('utf8')).toContain('Time-sensitive task');await expect(page.getByRole('button',{name:'Save changes'})).toBeVisible();
  const persisted=await(await owner.get(`/api/projects/${tenant.projectId}/tasks`)).json();expect(new Date(persisted.items.find((t:{id:string})=>t.id===task.id).due_at).toISOString()).toBe('2030-01-01T00:00:00.000Z');
});
test('search and next-page controls reflect persisted tasks',{tag:'@regression',annotation:forgeId('tb-ui-search')},async({page,tenant,owner})=>{
  for(let n=0;n<6;n++)await owner.post(`/api/projects/${tenant.projectId}/tasks`,{data:{title:`Find task ${n}`,status:n===5?'done':'todo'}});await loginPage(page,tenant);await expect(page.getByText('6 tasks · page 1',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.getByText('6 tasks · page 2',{exact:true})).toBeVisible();await page.getByLabel('Search tasks').fill('Find task 5');await expect(page.getByText('1 tasks · page 1',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Find task 5',exact:true})).toBeVisible();
});
