import { sha256, stableStringify, type AttemptRecord, type MergedRunResult } from '@azerish25-ux/forgeqa-core';
function xml(value:string):string{return value.replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]!));}
function html(value:string):string{return xml(value).replace(/`/g,'&#96;');}
function markdown(value:string):string{return value.replace(/\\/g,'\\\\').replace(/\|/g,'\\|').replace(/\r?\n/g,' ');}
function finalAttempts(run:MergedRunResult):AttemptRecord[]{const map=new Map<string,AttemptRecord>();for(const attempt of run.attempts){const current=map.get(attempt.executionId);if(!current||attempt.retry>=current.retry)map.set(attempt.executionId,attempt);}return [...map.values()];}
export function toJsonReport(run:MergedRunResult):string{return `${JSON.stringify(run,null,2)}\n`;}
export function toJUnit(run:MergedRunResult):string{const finals=finalAttempts(run);const failures=finals.filter((a)=>['failed','timed-out','unexpected-pass','cancelled'].includes(a.outcome)).length;const skipped=finals.filter((a)=>a.outcome==='skipped'||a.outcome==='expected-failure').length;const cases=finals.map((a)=>{const attrs=`name="${xml(a.logicalTestId)}" classname="${xml(a.executionId)}" time="${(a.durationMs/1000).toFixed(3)}"`;if(['failed','timed-out','unexpected-pass','cancelled'].includes(a.outcome))return `<testcase ${attrs}><failure message="${xml(a.error?.message??a.outcome)}">${xml(a.error?.stack??'')}</failure></testcase>`;if(a.outcome==='skipped'||a.outcome==='expected-failure')return `<testcase ${attrs}><skipped message="${xml(a.outcome)}"/></testcase>`;return `<testcase ${attrs}/>`;}).join('');return `<?xml version="1.0" encoding="UTF-8"?>\n<testsuite name="ForgeQA" tests="${finals.length}" failures="${failures}" skipped="${skipped}">${cases}</testsuite>\n`;}
export function toMarkdownSummary(run:MergedRunResult):string{const finals=finalAttempts(run);const lines=['# ForgeQA quality summary','',`- Run: \`${markdown(run.runId)}\``,`- Completion: **${run.completion}**`,`- Tests: ${finals.length}`,`- Attempts: ${run.attempts.length}`,`- Missing executions: ${run.missingExecutions.length}`,'','| Test | Outcome | Duration | Attempts |','|---|---:|---:|---:|'];for(const attempt of finals){const count=run.attempts.filter((a)=>a.executionId===attempt.executionId).length;lines.push(`| ${markdown(attempt.logicalTestId)} | ${attempt.outcome} | ${attempt.durationMs} ms | ${count} |`);}return `${lines.join('\n')}\n`;}
export function toHtmlReport(run:MergedRunResult):string{const rows=finalAttempts(run).map((a)=>`<tr data-outcome="${html(a.outcome)}"><td>${html(a.logicalTestId)}</td><td>${html(a.outcome)}</td><td>${a.retry+1}</td><td>${a.durationMs} ms</td><td><pre>${html(a.error?.message??'')}</pre></td></tr>`).join('');const payload=html(stableStringify(run));return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>ForgeQA report</title><style>body{font:16px system-ui;max-width:1200px;margin:auto;padding:2rem}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bbb;padding:.5rem;text-align:left}button{margin:.25rem}pre{white-space:pre-wrap}</style></head><body><h1>ForgeQA report</h1><p>Run <code>${html(run.runId)}</code> — <strong>${html(run.completion)}</strong></p><div role="group" aria-label="Outcome filters"><button type="button" data-filter="all">All</button><button type="button" data-filter="failed">Failed</button><button type="button" data-filter="passed">Passed</button></div><table><thead><tr><th>Test</th><th>Outcome</th><th>Attempts</th><th>Duration</th><th>Diagnostic</th></tr></thead><tbody>${rows}</tbody></table><details><summary>Machine data</summary><pre id="payload">${payload}</pre></details><script>for(const button of document.querySelectorAll('button[data-filter]'))button.addEventListener('click',()=>{const f=button.dataset.filter;for(const row of document.querySelectorAll('tbody tr'))row.hidden=f!=='all'&&row.dataset.outcome!==f;});</script></body></html>`;}
export function reportChecksums(outputs:Record<string,string>):Record<string,string>{return Object.fromEntries(Object.entries(outputs).map(([name,value])=>[name,sha256(value)]));}
