import {sha256,type AttemptRecord,type MergedRunResult} from '@azerish25-ux/forgeqa-core';
function xml(value:string):string{return value.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'�').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]!));}
function md(value:string):string{return xml(value).replace(/[`|\r\n]/g,' ').replace(/@/g,'＠');}
export function executions(run:MergedRunResult):Array<{final:AttemptRecord;attempts:AttemptRecord[];outcome:string;blocked:boolean}>{
  const map=new Map<string,AttemptRecord[]>();for(const a of run.attempts)map.set(a.executionId,[...(map.get(a.executionId)??[]),a]);
  return [...map.values()].map(attempts=>{attempts.sort((a,b)=>a.retry-b.retry);const final=attempts[attempts.length-1]!;const flaky=final.outcome==='passed'&&attempts.some(a=>['failed','timed-out'].includes(a.outcome));const outcome=flaky?'flaky':final.outcome;
    const blocked=['failed','timed-out','unexpected-pass','cancelled'].includes(outcome)||(run.gate?.violations.some(v=>v.affected?.includes(final.executionId)&&v.severity==='error')??false)||(flaky&&run.gate?.outcome==='fail');return {final,attempts,outcome,blocked};});
}
export function toJsonReport(run:MergedRunResult):string{return `${JSON.stringify(run,null,2)}\n`;}
export function toJUnit(run:MergedRunResult):string{
  const all=executions(run);const cases=all.map(e=>{const a=e.final,attrs=`name="${xml(a.title??a.logicalTestId)}" classname="${xml(a.project??a.executionId)}" time="${(e.attempts.reduce((n,v)=>n+v.durationMs,0)/1000).toFixed(3)}"`;const original=e.attempts.find(v=>v.error)?.error;const diagnostic=e.attempts.map(v=>`attempt ${v.retry}: ${v.outcome}\n${v.error?.message??''}`).join('\n');return `<testcase ${attrs}>${e.blocked?`<failure message="${xml(original?.message??e.outcome)}" type="${xml(e.outcome)}">${xml(diagnostic)}</failure>`:['skipped','expected-failure'].includes(e.outcome)?`<skipped message="${xml(e.outcome)}"/>`:''}<system-out>${xml(diagnostic)}</system-out></testcase>`;}).join('');
  const violations=run.gate?.violations.map(v=>`${v.id}: ${v.message}`).join('\n')??'';
  const evidence=run.evidence?.reconciliation.status??'not-available';
  return `<?xml version="1.0" encoding="UTF-8"?>\n<testsuite name="ForgeQA" tests="${all.length}" failures="${all.filter(v=>v.blocked).length}" skipped="${all.filter(v=>!v.blocked&&['skipped','expected-failure'].includes(v.outcome)).length}"><properties><property name="forgeqa.gate" value="${xml(run.gate?.outcome??'not-evaluated')}"/><property name="forgeqa.completion" value="${run.completion}"/><property name="forgeqa.nativeEvidence" value="${xml(evidence)}"/></properties>${cases}<system-err>${xml(violations)}</system-err></testsuite>\n`;
}
export function toMarkdownSummary(run:MergedRunResult):string{
  const all=executions(run);const evidence=run.evidence?`Native evidence: **${run.evidence.reconciliation.status}** · Blobs: ${run.evidence.nativeBlobCount} · Captured artifacts: ${run.evidence.capturedArtifacts}`:'Native evidence: **not available**';return ['# ForgeQA quality summary','',`Run: ${md(run.runId)}`,`Completion: **${run.completion}** · Gate: **${run.gate?.outcome??'not evaluated'}**`,evidence,`Tests: ${all.length} · Attempts: ${run.attempts.length} · Missing: ${run.missingExecutions.length}`,'','| Test | Project | First attempt | Final outcome | Attempts |','|---|---|---|---|---|',...all.map(e=>`| ${md(e.final.title??e.final.logicalTestId)} | ${md(e.final.project??'unknown')} | ${e.attempts[0]!.outcome} | ${e.outcome} | ${e.attempts.length} |`),'','## Gate violations',...(run.gate?.violations.length?run.gate.violations.map(v=>`- ${md(v.id)}: ${md(v.message)}`):['None recorded.']),''].join('\n');
}
export function toHtmlReport(run:MergedRunResult):string{
  const all=executions(run);const rows=all.map(e=>`<tr data-outcome="${xml(e.outcome)}"><td><strong>${xml(e.final.title??e.final.logicalTestId)}</strong><br/><small>${xml(e.final.logicalTestId)} · ${xml(e.final.project??'unknown')} · ${xml(e.final.environment??'unknown')}</small></td><td>${e.attempts[0]!.outcome}</td><td>${e.outcome}</td><td>${e.attempts.length}</td><td><details><summary>Attempts & evidence</summary>${e.attempts.map(a=>`<h3>Attempt ${a.retry+1}: ${a.outcome} (${a.durationMs} ms)</h3><pre>${xml(a.error?.message??'No assertion error recorded.')}</pre><ul>${(a.artifacts??[]).map(file=>`<li>${xml(file.type)}: ${file.state}${file.state==='captured'&&/^(attachments|artifacts)\/[\w./-]+$/.test(file.path)&&!file.path.split('/').includes('..')?` — <a href="${xml(file.path)}">${xml(file.path)}</a>`:''}${file.size===undefined?'':` (${file.size} bytes)`}</li>`).join('')}</ul>`).join('')}</details></td></tr>`).join('');
  const evidence=run.evidence?`<p><strong>Native evidence: ${xml(run.evidence.reconciliation.status)}</strong> · ${run.evidence.nativeBlobCount} blob reports · ${run.evidence.capturedArtifacts} captured artifacts · ${run.evidence.missingArtifacts} missing declarations · ${run.evidence.unavailableArtifacts} unavailable declarations</p><p><a href="${xml(run.evidence.nativeReport)}">Open merged Playwright report</a> · <a href="${xml(run.evidence.artifactManifest)}">Artifact manifest</a> · <a href="${xml(run.evidence.nativeJson)}">Native JSON evidence</a></p>`:'<p>Native distributed evidence was not attached to this report.</p>';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ForgeQA · Test evidence</title><style>body{font:15px system-ui;background:#f3f5f5;color:#1c3034;margin:auto;max-width:1300px;padding:32px}h1{font-size:34px}table{border-collapse:collapse;width:100%;background:white}th,td{padding:16px;border-bottom:1px solid #d7e0e1;text-align:left;vertical-align:top}th{background:#173b40;color:white}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-width:620px}small{color:#55686d}input,select{font:inherit;padding:10px;margin:8px;border:1px solid #a8bbc0}section{background:white;padding:18px;margin:20px 0}a:focus-visible,summary:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #af7222}h3{font-size:14px}.scroll{overflow:auto}</style></head><body><h1>ForgeQA test evidence</h1><p>Run <code>${xml(run.runId)}</code></p><section><strong>Gate: ${run.gate?.outcome??'not evaluated'} · ${run.completion}</strong><p>${all.length} tests · ${run.attempts.length} attempts · ${all.filter(e=>e.outcome==='flaky').length} retry-recovered · ${run.missingExecutions.length} missing executions</p>${evidence}<p>Historical comparison: NO_BASELINE. This report does not invent historical reliability.</p><ul>${(run.gate?.violations??[]).map(v=>`<li>${xml(v.id)}: ${xml(v.message)}</li>`).join('')}</ul></section><label>Search tests<input id="search" type="search"></label><label>Outcome<select id="outcome"><option value="all">All</option>${['passed','failed','flaky','timed-out','expected-failure','unexpected-pass','skipped','cancelled'].map(v=>`<option>${v}</option>`).join('')}</select></label><div class="scroll"><table><thead><tr><th>Test</th><th>First attempt</th><th>Final outcome</th><th>Attempts</th><th>Evidence</th></tr></thead><tbody>${rows}</tbody></table></div><p>Traces, videos and screenshots can contain sensitive data. Only synthetic captures belong in public demonstrations.</p><script>const s=document.getElementById('search'),o=document.getElementById('outcome');function filter(){for(const r of document.querySelectorAll('tbody tr'))r.hidden=!(r.textContent.toLowerCase().includes(s.value.toLowerCase())&&(o.value==='all'||r.dataset.outcome===o.value));}s.addEventListener('input',filter);o.addEventListener('change',filter);</script></body></html>`;
}
export function reportChecksums(outputs:Record<string,string>):Record<string,string>{return Object.fromEntries(Object.entries(outputs).map(([name,value])=>[name,sha256(value)]));}
