#!/usr/bin/env node
import { access, lstat, mkdir, readFile, realpath, rename, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve, isAbsolute } from 'node:path';
import { pathToFileURL } from 'node:url';
import { parse, planCommand, runCommand, doctorCommand, type Parsed } from './runner.js';
import { ConfigurationError, evaluateGates, toForgeError, type MergedRunResult, type QuarantineRecord } from '@azerish25-ux/forgeqa-core';
import { mergeShardResults, toHtmlReport, toJsonReport, toJUnit, toMarkdownSummary } from '@azerish25-ux/forgeqa-reporter';
import { calculateReliability, validateQuarantine } from '@azerish25-ux/forgeqa-flake-analysis';
import {initCommand} from './init.js';
const VERSION='0.1.0';
function jsonMode(parsed:Parsed):boolean{return parsed.options.get('json')===true;}
function emit(parsed:Parsed,value:unknown,human:string):void{process.stdout.write(jsonMode(parsed)?`${JSON.stringify(value)}\n`:`${human}\n`);}
function rootSafe(root:string,path:string):string{const full=resolve(root,path);const rel=relative(root,full);if(rel.startsWith('..')||isAbsolute(rel))throw new ConfigurationError(`Path escapes destination: ${path}`);return full;}
async function atomicWrite(path:string,content:string):Promise<void>{await mkdir(dirname(path),{recursive:true});const temp=`${path}.${process.pid}.tmp`;await writeFile(temp,content,{flag:'wx'});await rename(temp,path);}
async function loadJson(path:string):Promise<any>{return JSON.parse(await readFile(resolve(path),'utf8'));}
async function reportMerge(parsed:Parsed):Promise<void>{const manifestPath=String(parsed.options.get('manifest')||'');if(!manifestPath||!parsed.positionals.length)throw new ConfigurationError('report merge requires --manifest and shard report paths.');const manifest=await loadJson(manifestPath);const shards=await Promise.all(parsed.positionals.map(loadJson));const merged=mergeShardResults(shards,manifest);const output=String(parsed.options.get('output')||'forgeqa-results');await mkdir(output,{recursive:true});await Promise.all([atomicWrite(resolve(output,'report.json'),toJsonReport(merged)),atomicWrite(resolve(output,'junit.xml'),toJUnit(merged)),atomicWrite(resolve(output,'summary.md'),toMarkdownSummary(merged)),atomicWrite(resolve(output,'index.html'),toHtmlReport(merged))]);emit(parsed,{output,completion:merged.completion},`Merged ${shards.length} shards into ${output}.`);if(merged.completion!=='complete')process.exitCode=3;}
async function gate(parsed:Parsed):Promise<void>{const run=await loadJson(String(parsed.options.get('report')||parsed.positionals[0]||'')) as MergedRunResult;let quarantines:QuarantineRecord[]=[];try{quarantines=await loadJson(String(parsed.options.get('quarantine')||'.forgeqa/quarantine.json'));}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw new ConfigurationError('Quarantine file is invalid or unreadable.');}const decision=evaluateGates(run,quarantines,{failOnRetryRecovered:true,unexpectedSkipBudget:0,requireCompleteShards:true,maxQuarantineEntries:20});emit(parsed,decision,decision.violations.length?decision.violations.map((v)=>`${v.severity.toUpperCase()} ${v.id}: ${v.message}`).join('\n'):'All quality gates passed.');if(decision.outcome==='fail')process.exitCode=1;}
async function flakes(parsed:Parsed):Promise<void>{const run=await loadJson(String(parsed.options.get('report')||parsed.positionals[0]||'')) as MergedRunResult;const metrics=calculateReliability(run.attempts,Number(parsed.options.get('minimum-samples')||20));emit(parsed,metrics,JSON.stringify(metrics,null,2));}
async function quarantineValidate(parsed:Parsed):Promise<void>{const records=await loadJson(String(parsed.options.get('file')||'.forgeqa/quarantine.json')) as QuarantineRecord[];const tests=String(parsed.options.get('known-tests')||records.map((r)=>r.testId).join(',')).split(',').filter(Boolean);const result=validateQuarantine(records,tests);emit(parsed,result,result.errors.concat(result.warnings).join('\n')||'Quarantine policy is valid.');if(!result.valid)process.exitCode=1;}
function help():string{return `ForgeQA ${VERSION}\n\nCommands:\n  forgeqa init [--destination DIR] [--package-manager npm|pnpm] [--dry-run] [--json]\n  forgeqa doctor [--json]\n  forgeqa plan [--suite NAME] [--browsers LIST] [--workers N] [--shard I/N] [--json]\n  forgeqa run [selection options] [--config FILE] [--playwright-config FILE] [--json]\n  forgeqa repeat\n  forgeqa report merge --manifest FILE --output DIR SHARD...\n  forgeqa report serve\n  forgeqa history import\n  forgeqa flakes --report FILE\n  forgeqa quarantine validate [--file FILE]\n  forgeqa quarantine add|remove\n  forgeqa gate --report FILE\n  forgeqa migrate\n\nExit codes: 0 compliant success, 1 quality failure, 2 usage/configuration, 3 infrastructure/report integrity, 130 interruption.\n`;}
export async function main(argv=process.argv.slice(2)):Promise<void>{const parsed=parse(argv);const key=parsed.command.join(' ');if(parsed.options.has('version')||key==='version'){process.stdout.write(`${VERSION}\n`);return;}if(!key||parsed.options.has('help')||key==='help'){process.stdout.write(help());return;}if(parsed.options.has('version')||key==='version'){process.stdout.write(`${VERSION}\n`);return;}switch(key){case'init':await initCommand(parsed);break;case'doctor':await doctorCommand(parsed);break;case'plan':await planCommand(parsed);break;case'run':await runCommand(parsed);break;case'report merge':await reportMerge(parsed);break;case'gate':await gate(parsed);break;case'flakes':await flakes(parsed);break;case'quarantine validate':await quarantineValidate(parsed);break;case'repeat':case'report serve':case'history import':case'quarantine add':case'quarantine remove':case'migrate':throw new ConfigurationError(`${key} requires project-specific inputs and is intentionally fail-closed in this source release.`);default:throw new ConfigurationError(`Unknown command: ${key}`);}}
const entrypoint=process.argv[1];
if(entrypoint && import.meta.url===pathToFileURL(entrypoint).href) main().catch((error:unknown)=>{
  const forge=toForgeError(error);
  if(process.argv.includes('--json')) process.stdout.write(JSON.stringify({exitCode:forge.exitCode,error:{code:forge.code,message:forge.message,details:forge.details}})+'\n');
  else {process.stderr.write(`${forge.code}: ${forge.message}\n`);if(Object.keys(forge.details).length)process.stderr.write(JSON.stringify(forge.details)+'\n');}
  process.exitCode=forge.exitCode;
});
