import { VERSION } from './version.js';
export function templateFiles(packageManager:'npm'|'pnpm',template:'demo'|'existing'='demo'):Record<string,string>{
  const demo=template==='demo';
  const manifest={name:'forgeqa-consumer',version:'0.0.0',private:true,type:'module',packageManager:packageManager==='pnpm'?'pnpm@10.34.5':'npm@10.9.2',scripts:{test:'forgeqa run --suite release','test:native':'playwright test','test:plan':'forgeqa plan --suite release',...(demo?{start:'node demo-server.mjs'}:{})},devDependencies:{'@azerish25-ux/forgeqa-cli':VERSION,'@azerish25-ux/forgeqa-core':VERSION,'@azerish25-ux/forgeqa-playwright':VERSION,'@playwright/test':'1.58.2',typescript:'5.8.3'}};
  return {
    'package.json':JSON.stringify(manifest,null,2)+'\n',
    'forgeqa.config.ts':`import {defineForgeConfig} from '@azerish25-ux/forgeqa-core';\nexport default defineForgeConfig({project:'forgeqa-consumer',environments:{local:{baseUrl:process.env.BASE_URL??'http://127.0.0.1:3219'}},browsers:['chromium'],workers:2,retries:0});\n`,
    'playwright.config.ts':`import {defineForgePlaywrightConfig} from '@azerish25-ux/forgeqa-playwright';\nimport config from './forgeqa.config.js';\nexport default defineForgePlaywrightConfig(config,{testDir:'./tests/e2e',fullyParallel:true,${demo?"webServer:{command:'node demo-server.mjs',url:'http://127.0.0.1:3219/health',reuseExistingServer:false,timeout:15000,gracefulShutdown:{signal:'SIGTERM',timeout:3000}},":''}projects:[{name:'api',testMatch:'**/*.api.spec.ts'},{name:'chromium',testMatch:'**/*.ui.spec.ts',use:{browserName:'chromium'}}]});\n`,
    '.env.example':'BASE_URL=http://127.0.0.1:3219\n',
    '.gitignore':'node_modules/\nforgeqa-results/\nplaywright-report/\ntest-results/\n.env\n.auth/\n',
    '.forgeqa/quarantine.json':'[]\n',
    'tests/e2e/fixtures.ts':`import {test as base,expect} from '@playwright/test';\nimport {createForgeTest} from '@azerish25-ux/forgeqa-playwright';\nexport const test=createForgeTest(base);\nexport {expect};\n// Add application-owned API authentication adapters here. Never reuse mutable accounts across workers.\n`,
    'tests/e2e/smoke.api.spec.ts':`import {test,expect} from './fixtures.js';\ntest('health is reachable',{tag:'@smoke'},async({request})=>{const response=await request.get('${demo?'/health':'/'}');expect(response.ok()).toBe(true);${demo?"expect(await response.json()).toEqual({status:'ready'});":''}});\n`,
    'tests/e2e/smoke.ui.spec.ts':`import {test,expect} from './fixtures.js';\ntest('application renders',{tag:'@smoke'},async({page})=>{await page.goto('/');await expect(${demo?"page.getByRole('heading',{name:'ForgeQA consumer'})":"page.locator('body')"}).toBeVisible();});\n`,
    ...(demo?{'demo-server.mjs':`import {createServer} from 'node:http';\nconst server=createServer((req,res)=>{if(req.url==='/health'){res.setHeader('content-type','application/json');res.end(JSON.stringify({status:'ready'}));}else{res.setHeader('content-type','text/html');res.end('<!doctype html><html lang="en"><title>ForgeQA consumer</title><body><h1>ForgeQA consumer</h1><p>This minimal onboarding harness is not the TeamBoard application.</p></body></html>');}});\nserver.listen(3219,'127.0.0.1');\nprocess.on('SIGTERM',()=>server.close(()=>process.exit(0)));\n`}:{}),
    '.github/workflows/forgeqa.yml':`name: ForgeQA\non: [push, pull_request]\npermissions: { contents: read }\njobs:\n  quality:\n    runs-on: ubuntu-latest\n    timeout-minutes: 15\n    steps:\n      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6\n        with: { persist-credentials: false }\n      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5\n        with: { node-version: 22, package-manager-cache: false }\n${packageManager==='pnpm'?"      - run: npm install --global pnpm@10.34.5\n      - run: pnpm install --frozen-lockfile\n":"      - run: npm ci --ignore-scripts\n"}      - run: ${packageManager==='pnpm'?'pnpm exec':'npx --no-install'} playwright install --with-deps chromium\n      - run: ${packageManager==='pnpm'?'pnpm test':'npm test'}\n      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4\n        if: always()\n        with: { name: synthetic-forgeqa-results, path: forgeqa-results/, retention-days: 7, if-no-files-found: error }\n`,
    'FORGEQA.md':`# ForgeQA ${template} consumer\n\nGenerated for ForgeQA ${VERSION}. Use matching package versions; generated configuration is not proof of a public npm publication. Before publication, install the packed candidate packages with matching versions. Installation is explicit: ${packageManager} install. Generate and commit its lockfile before CI. Then install matching Chromium with ${packageManager==='pnpm'?'pnpm exec':'npx --no-install'} playwright install chromium.\n\nRun forgeqa doctor, forgeqa plan --suite release, and forgeqa run --suite release. The native playwright test entrypoint also enforces strict policy. Retry recovery is not a clean pass.\n\n${demo?'The packaged HTTP harness starts automatically through native Playwright webServer. It proves onboarding, not TeamBoard or PostgreSQL integration.':'Existing application: configure BASE_URL, readiness, and your own authentication/data adapters. ForgeQA cannot infer arbitrary application semantics. Existing configuration is never overwritten; resolve the reported integration conflicts explicitly.'}\n\nStorage state is a credential: keep it temporary and out of artifacts. The seven-day upload example is for synthetic data; do not expose private traces in a public repository.\n`
  };
}
